<div id="main">
    <div class="container">	
        <div class="row">
            <div class="col-md-5 col-xs-12">
                    <img src="app/img/img6.jpg" alt="Foto Cidade Canudos" id="img6" class="img-responsive">
            </div>
    
            <div class="col-md-7 col-xs-12">
                <h1 id="">Canudos Ontem e Hoje</h1>
                    <p id="CANUDOS, 120 ANOS">Canudos Ontem e Hoje é um projeto do CEPESC para tornar a história de Canudos conhecida e celebrada em Salvador anualmente, na primeira semana de outubro, lembrando a fundação do Arraial do Belo Monte de Antonio Conselheiro, em 1893, a sua destruição, em 1897, e o longo processo e a luta para a sua ressurreição e o resgate histórico. </p>
            </div>
        </div>
    </div>
</div>

<div id="content">

    <aside class="sidebar">
            <div class="col-md-12 col-xs-12">
                <h3>índice</h3>
                    <ul>
                        <li><a href="#CANUDOS, 120 ANOS">CANUDOS, 120 ANOS</a></li>
                    </ul>
            </div>
    </aside>
    <div class="wrapper">
    <div class="container">	
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <div class="artigo">
                    <h2>CANUDOS, 120 ANOS</h2>
                    <cite>Pr. Djalma Torres<cite>
                    <p>A cidade de Canudos é uma cidade como outra qualquer do Nordeste brasileiro, com cerca de 15 mil habitantes. Acontece que, para além de sua aparente insignificância há uma história de muito vigor em todo o país, que completa este ano de 2017, 120 anos de sua destruição.</p>
                    <p>Neste texto há uma abordagem sobre o protagonista dessa epopeia, a comunidade por ele organizada, bem como o contexto em que tudo aconteceu, o fim de tudo e a ressurreição surpreendente.</p>
                    <h3>I.ANTONIO CONSELHEIRO</h3>
                    <p>É este o homem que protagonizou toda esta história de Canudos.</p>
                    <h4></h4>
                    <p>Antonio Vicente Mendes Maciel, o Antonio Conselheiro, nasceu no dia 13 de março de 1830, em terras da Fazenda Santo Antonio do Boqueirão, Vila de Santo Antonio de Quixeramobim, no Ceará. Era filho de Vicente Mendes Maciel, comerciante e construtor de casas, e de Maria Joaquina de Jesus, conhecida como Maria Chana. Era sobrinho-neto de Antonio Maciel, assassinado, juntamente com o irmão, Miguel Carlos Maciel, avô paterno do Conselheiro, a mando dos Araújo e Veras, em 9 de junho de 1833. Foi batizado na Matriz da Cidade de Quixeramobim, no dia 22 de maio de 1830, pelo vigário Domingos Álvares Vieira, como filho natural de Maria Joaquina, por não serem os seus pais casados, o que aconteceu somente em 31 de agosto de 1834, provavelmente por motivo de doença da mãe, pois pouco tempo depois ela morreu, deixando órfãos de mãe, além de Antonio Vicente, duas filhas, Francisca e Maria. Foram padrinhos de batismo Gonçalo Nunes Leitão e Maria Francisca de Paula.</p>
                    <p>Antonio Vicente Mendes Maciel, teve uma infância atribulada. Em 1833, teve início uma luta sangrenta entre a sua família e os Araújos, muito poderosa na região, que resultou na morte, entre outras, de seu avô, Miguel Mendes Maciel, que desfrutava de boa reputação na Cidade. Nessa época era Juiz de Direito da Comarca de Quixeramobim, o Dr. Ibiapina, amigo dos Maciel, que tentara dissuadir Miguel Mendes Maciel de vingar o duplo assassinato do pai e do tio. Ibiapina foi sucedido no cargo pelo juiz leigo Antonio Duarte de Queiroz, parente dos Araújos, que viria insuflar a perseguição aos ancestrais do Conselheiro.</p>
                    <p>Em 8 de fevereiro de 1837, o pai de Antonio Conselheiro casou-se novamente. Esta sua segunda esposa, Francisca Maria da Conceição, que depois de casada passou a se chamar Francisca Maria Maciel, uma artesã, era muito geniosa. Desse casamento nasceram duas filhas: Dorotéia e Rufina. Logo começou a maltratar os enteados e depois se desentendeu com o esposo.</p>
                    <p>O menino Antonio Vicente depois de iniciar os seus estudos com um dos amigos de seu pai, foi colocado pelo pai na escola do professor Manuel Antônio Ferreira Nobre, um famoso educador da região. Com ele Antonio Conselheiro estudou Aritmética, Geografia, Português, Francês e Latim.</p>
                    <p>Era tido como um aluno aplicado e inteligente. Tinha como suas leituras preferidas na época, O Lunário Perpétuo, de Jerônimo Cortez Valenciano, A princesa Magelona e As guerras do imperador Carlos Magno e os Doze pares da Inglaterra. Tinha, o jovem Antonio Vicente Maciel, preferência acentuada pelas leituras instrutivas, românticas e heroicas.</p>
                    <p>Na luta com os Araújos, ficaram ao lado de sua família, dois personagens importantes na vida de Antonio Vicente Mendes Maciel: o jornalista e escritor João Brígido, que descreveu a luta sangrenta entre as duas famílias e o já mencionado juiz da Comarca de Quixeramobim José Antonio Pereira de Ibiapina, que mais tarde viria a ser o Padre Ibiapina, famoso em todo o sertão. O Juiz tentou amenizar o ódio entre as duas famílias, sem sucesso.</p>
                    <p>Assim, pode-se dizer que a infância de Antonio Vicente Mendes Maciel foi bastante perturbada.</p>
                    <h4>2.Juventude e atividades</h4>
                    <p>No dia 5 de abril de 1855, quando Antonio Conselheiro tinha 25 anos de idade, morreu o seu pai. Ele teve que assumir as dívidas e a direção dos negócios da família e tomar conta das três irmãs ainda solteiras, até casá-las.</p>
                    <p>Nesse período difícil de sua juventude ele conseguiu saldar as dívidas do pai. Perdeu a madrasta que morreu aos 39 anos de idade, desequilibrada mentalmente. E casou as três irmãs. Uma delas, Francisca, casou-se com Lourenço Correia Lima e residiam em Paus Brancos, Município de Quixeramobim. Em 1857, no dia 7 de janeiro, (1º de janeiro, segundo Edmundo Moniz, fl.24) também ele se casou, com Brasilina Laurentina de Lima, filha natural de Francisca Pereira de Lima, na Matriz de Quixeramobim, pelo padre Jacinto Borges. Brasilina, que aparentava uns 18 anos de idade, era alta, magra, de cor branca e bonita. Segundo Calasans, ela era prima do Conselheiro, tinha uma vida irregular e leviana, tendo sido abandonada pelo marido por sua notória infidelidade.   </p>
                    <p>Antono Vicente não tinha vocação comercial. O negócio herdado do pai ia mal. Ele se desfez da casa comercial, da casa onde morava, deixou Quixeramobim e se transferiu para a Fazenda do Tigre, nas vizinhanças, abrindo uma escola primária onde ensinava português, aritmética e geografia. Nesse tempo nasceu o primeiro filho do casal.</p>
                    <p>Pouco tempo depois mudou-se para Tamboril e de lá para Campo Grande, onde conseguiu um emprego de caixeiro numa casa comercial, que mais tarde foi fechada, porque o dono mudou de profissão. Antonio Vicente ficou desempregado no momento em que nasceu o seu segundo filho. Passou a exercer em Campo Grande mesmo, e posteriormente em Itu, as funções de advogado provisionado, onde exercia o cargo para defender os pobres.</p>
                    <p>Aí a vida de Antonio Vicente sofreu um grande revés. A esposa Brasilina fugiu com um furriel (antigo posto militar entre cabo e sargento ) da polícia cearense, deixando-lhe os dois filhos do casal. Segundo Edmundo Moniz, a esposa ficou com os filhos, cujo destino não se soube mais. Com a vida tumultuada pelo abandono da mulher e em conflito com os coronéis e as autoridades da região, Antonio Vicente Mendes Maciel deixou a advocacia e voltou às aulas, agora na fazenda do Major José Gonçalves Veras.   </p>
                    <p>Depois do sofrimento com o abandono da esposa, Antonio Vicente Maciel conheceu, em Santa Quitéria, Joana Imaginária, com quem passou a conviver. Joana era muito mística e esculpia santos de barro e madeira. Com ela Antonio Conselheiro teve um filho, Joaquim Aprígio. Mas a união entre os dois durou pouco tempo, porque Joana se negou a segui-lo em suas andanças pelo sertão. Preferiu continuar a fazer os seus santos para atender à freguesia que chegava das cidades vizinhas, criar o filho do casal num ambiente mais sossegado e a continuar ali mesmo a sua vida religiosa. Passou a acompanhar de longe a vida de Antonio Vicente Mendes Maciel.</p>
                    <p>Foram muitos os anos de andanças, marcados por insegurança e instabilidade através de várias regiões do Estado do Ceará e o exercício de diversas atividades sem sucesso. Essa peregrinação pelo interior do Ceará e o exercício da advocacia em defesa dos empobrecidos da época, ajudaram Antonio Vicente a firmar uma posição contra os poderosos de sua terra e a se conscientizar dos pecados da sociedade de seu tempo.</p>
                    <p>Edundo Moniz descreve este momento assim:</p>
                    <blockquote>“A instabilidade nos empregos, a contínua mudança de residência e a passagem pelas cidades em vários municípios do centro e do sul da província fizeram com que observasse e tomasse contato com a realidade social do sertão, com a vida incerta e miserável dos camponeses e a intolerância senhorial dos grandes latifundiários”.</blockquote>
                    <p>Estava no final de gestação a transformação da vida de Antonio Vicente Mendes Maciel. Não só a sua longa e dolorosa experiência de trabalho e desacertos, mas também, e sobretudo, o cabedal religioso que acumulou aos longo dos anos.</p>
                    <h4>3.O nível intelectual de Antonio Conselheiro</h4>
                    <p>Antonio Conselheiro estava muito acima do padrão cultural do povo nordestino com quem convivia. Ele revelou conhecimento não somente da Bíblia, tanto o Antigo como o Novo Testamento. Conhecia também muitos autores da Igreja, como São Jerônimo, São Basílio, que pregava contra a riqueza, São Cristóvão, que defendia um retorno da Igreja ao cristianismo primitivo, Santo Agostinho, São Boaventura, Santo Tomás de Aquino, Santo Inácio de Loyola e outros.</p>
                    <p>Mas não só autores religiosos. Antonio Conselheiro devia conhecer autores como Homero e Virgílio e alguns estudiosos de Canudos chegam a afirmar que ele conhecia A Utopia, de Tomás Morus.</p>
                    <h4>4. A experiência religiosa de Antonio Conselheiro</h4>
                    <p>Antonio Conselheiro desde cedo tinha recebido formação religiosa. Era considerado em Quixeramobim como muito religioso: Alexandre Otten, cita Montenegro sobre o assunto:</p>
                    <blockquote>“Antonio Conselheiro revelava-se muito religioso, morigerado e bom, respeitoso para com os velhos. Protegia e era carinhoso com as crianças. Sofria com as rusgas entre o pai e a madrasta. Consideravam-no a pérola de Quixeramobim, por ser um moço sério, trabalhador, honesto e religioso “.</blockquote>
                    <p>No período de turbulência de sua vida, entre 1869 e 1871 foi visto acompanhando os missionários que evangelizavam na região.</p>
                    <p>Antonio Conselheiro recebeu três fortes influências em sua vida religiosa: A Bíblia Sagrada, A Missão Abreviada e o Pe. Ibiapina.</p>
                    <h5>A influência da Bíblia</h5>
                    <p>Antonio conselheiro não devia possuir uma Bíblia, que era um livro raro na época. Por isso copiou o Livro de Êxodo, os Evangelhos, o Livro de Atos dos Apóstolos, As Cartas de Paulo e o Livro de Apocalípse, que fazia uso em suas pregações.</p>
                    <h5>A Missão Abreviada</h5>
                    <p>A Missão Abreviada era uma espécie de livro de cabeceira de Antonio Conselheiro. Era um devocionário. Dele Antonio Conselheiro tirava muitas de suas pregações e de seus pensamentos.</p>
                    <p>A Missão Abreviada foi escrita pelo padre português José Gonçalves Couto. O título original era Missão Abreviada para Despertar os Descuidados, Converter os pecadores e Sustentar o Fruto das Missões. Tinha 993 páginas, com 211 meditações e instruções. O objetivo do livro era levar os fiéis à conversão e à correção dos seus pecados, em preparação para a confissão.</p>
                    <h5>A influência do Padre Ibiapina</h5>
                    <p>Como já dissemos, Antonio Vicente Mendes Maciel conhecia desde pequeno o Padre Ibiapina porque ele, como juiz de Quixeramobim, defendeu a sua família contra os Araújos.</p>
                    <p>José Antonio de Maria Ibiapina, nasceu em 1805. Era filho de Francisco Miguel Pereira e Teresa Maria de Jesus. Era natural do povoado de Ibiapina, Município de Sobral, no Ceará. O “Ibiapina“ foi uma homenagem do pai ao local onde viveu muitos anos. Aos 19 anos de idade, o jovem Ibiapina perdeu o pai e o irmão na repressão que seguiu a revolução de 1824, - Confederação do Equador - que pretendia instalar no Nordeste a “República do Equador“. O pai foi fuzilado e o irmão desterrado na ilha de Fernando de Noronha, onde foi assassinado clandestinamente. Ele já havia perdido a mãe anteriormente.</p>
                    <p>José Antonio, que se preparava para o sacerdócio no Seminário de Olinda, em Pernambuco, foi forçado a voltar para o Ceará, a fim de assumir a responsabilidade pelos irmãos menores</p>
                    <p>Depois de resolver os problemas familiares voltou para Recife. Ingressou na Faculdade de Direito de Pernambuco, em 1828, fazendo parte da primeira turma da Faculdade recém inaugurada. Pertenceu à primeira turma de bacharéis formados no Brasil. Na mesma Faculdade, logo após a sua formatura, organizou o curso de direito romano, do qual também era professor.</p>
                    <p>Um ano depois de formado voltou para o Ceará e foi nomeado Juiz de Direito e Chefe de Polícia em Quixeramobim, onde ficou menos de um ano, por constatar que o poder judiciário estava nas mãos dos coronéis da região. Em 1833 foi eleito Deputado Geral para representar o Ceará. Teve um desempenho muito bom, mas não quis disputar um segundo mandato, desanimado com o ambiente de corrupção e clientelismo da política brasileira.</p>
                    <p>Regressou a Recife e advogou durante os anos de 1838 a 1850 também na Paraíba, tornando-se famoso pela defesa dos pobres. Algum tempo depois dedicou-se à vida contemplativa.</p>
                    <p>Em 1853 aceitou o sacerdócio, passando pelo subdiaconato, diaconato e presbitério, sem a exigência de ingresso no Seminário, porque já era um profundo conhecedor da Igreja e de teologia.</p>
                    <p>Após a ordenação para o sacerdócio, foi nomeado vigário geral e professor do Seminário, funções que ocupou por dois anos. Devido ao seu prestígio como homem público e nível cultural, logo a sua importância cresceu dentro da Igreja. Era citado para uma próxima promoção episcopal. Mas, em lugar de uma carreira religiosa brilhante, optou por uma vida simples e de sacrifícios junto com os pobres. Em 1855, deixou tudo e foi para o sertão aproveitando, como pretexto, uma epidemia de cólera que atingiu os estados de Pernambuco e da Paraíba.</p>
                    <p>Até o ano de 1875 dedicou-se a pregar para os sertanejos. Era um orador brilhante e reunia sempre ao seu redor, para ouvi-lo, uma grande multidão. Percorreu os estados de Pernambuco, Paraíba, Piauí, Ceará e Rio Grande do Norte, numa peregrinação incessante, andando a pé e no lombo de burro, onde angariava donativos para ajudar aos pobres e necessitados desses Estados.</p>
                    <p>Ao lado do seu trabalho com as missões, o Padre Ibiapina conseguiu mobilizar os sertanejos para a construção de vinte duas casas de caridade, hospitais, cemitérios e igrejas. As casas de caridade que tinham como objetivos recolher órfãos, tiveram as suas funções ampliadas, servindo como hospitais, escolas e centros de assistência a pessoas e famílias pobres e desamparadas da região, em substituição ao trabalho do governo que nem chegava a esses locais ermos e abandonados.</p>
                    <p>Era considerado um santo por parcela considerável de nordestinos. A sua chegada nos povoados era sempre um acontecimento especial, com recepção por comitivas com faixas, flores e foguetes.</p>
                    <p>A caminhada pelo sertão acabou em 1876. O já então famoso Padre Ibiapina tinha ficado paralítico e passou a restringir suas atividades à Casa de Santa Fé de Arara, na Paraíba, centro de sua vida missionária, onde morreu, no dia 19 de fevereiro de 1883</p>
                    <p>Segundo Edmundo Moniz, Antonio Maciel reencontrou o padre Ibiapina no auge de sua glória e teve a oportunidade de trocar idéias com ele e de ouvir as suas audaciosas pregações. Durante algum tempo, seguiu-o como um discípulo, tomando-o como exemplo para a vida que deveria adotar. (27)</p>
                    <p>Ao morrer o Pe. Ibiapina, em 1883, Antonio Vicente Mendes Maciel, que o tinha como mestre e exemplo de vida, já se tornara famoso no sertão. Ele estava seguindo os passos do grande sacerdote, mas diferentemente dele, não aceitou o sacerdócio. Seguiu em frente como um beato.</p>
                    <h4>5. As peregrinações de Antonio Conselheiro</h4>
                    <p>A peregrinação de Antonio Conselheiro começa em 1858, quando tinha apenas 28 anos de idade e termina em Canudos, em 1893, onde morre, um pouco antes da destruição da Belo Monte sonhada e transformada em realidade por ele, mas que, lamentavelmente, teve tão poucos anos de vida. Para melhor se compreender essa maratona de deslocamentos, vou enumerá-las:</p>
                    <p>01.Em 1858 deixa a Fazenda Tigre, em Quixeramobim, no Ceará, e se fixa, com a família, em Tamboril, também no Ceará.</p>
                    <p>02. Em 1859 passa por Sobral (CE) e segue para Campo Grande, atual Guaraciaba do Norte (CE), onde se dedica ao comércio.</p>
                    <p>03. Em 1861 vai para Ipu (CE), com a família. Lá trabalha como solicitador ou requerente do Forum. Aí, com o fim do seu casamento, regressa a Tamboril (CE), passando a morar na Fazenda Santo Amaro.</p>
                    <p>04. Entre 1863 a 1865 vive em Santa Quitéria (CE) e se casa com Joana Imaginária, com quem tem o filho Joaquim Aprígio. É a partir dessa data que passa a ser identificado como Antonio Conselheiro.</p>
                    <p>05. Entre 1869 a 1871, depois de correr vários povoados, retorna a Quixeramobim e vai morar na Fazenda Várzea da Pedra.</p>
                    <p>06. Em 1870 há um provável encontro do Conselheiro com o Padre Ibiapina, na Cidade do Crato, no Ceará.</p>
                    <p>07. Em 1871, no dia 14 de outubro, no Forum de Quixeramobim, vence uma ação de cobrança no valor de sessenta mil reis, acionada por José Nogueira do Amorim.</p>
                    <p>08. Em 1873 passa pela fazenda Urucu (Assaré), de propriedade de José Francisco de Assunção, pai dos irmãos Vilanova, e ingressa no Estado de Pernambuco.</p>
                    <p>09. Livre dos compromissos que até então o prendiam e fortalecido pelas experiências de fé no acompanhamento das missões e do Padre Ibiapina, Antonio Vicente Mendes Maciel se tornou um peregrino e penitente. Em 1874 passa pelas cidades sergipanas de Estância, Itabaiana, Lagarto, Riachão das Dantas e Vila Canária. Em Estância é chamado de Antonio dos Mares. Reune um grupo de pessoas ao seu redor e recupera uma capela da Cidade.</p>
                    <p>Sua passagem por Sergipe é noticiada pelo jornal semanal “O RABUDO” que escreve a seu respeito:</p>
                    <blockquote>Algumas pessoas de juiso são acordes que esse homem cometteo um grande crime, e procura espiá-lo, ou encobri-lo por esta forma: não aceita esmolas, e a sua alimentação é a mais resumida e simples possivel. Pedimos providências a respeito. Seja esse homem capturado e levado à presença do Governo Imperial, afim de prevenir os males que ainda não foram postos em prática pela autoridade da palavra do Fr. S. Antonio dos Mares moderno. (28)</blockquote>
                    <p>10. De Sergipe vai para Missão de Saúde, atual Itapicuru, na Bahia, onde prega, dá conselhos e resiste aos seus oponentes, o vigário da paróquia da Cidade e as autoridades que se sentiam por ele atingidas, até que, em 1876, é preso sob a acusação de ser foragido da justiça do Ceará por ter matado a mãe e a esposa. Era uma acusação falsa, como foi provada logo em seguida. A mãe havia falecido quando ele era ainda criança e a esposa que o deixara estava viva.</p>
                    <p>Foi levado preso para Salvador, tendo sido espancado durante o percurso pelos soldados, que ainda lhe rasparam a cabeça. De Salvador foi escoltado para Fortaleza, no Ceará. No ofício datado de 5 de junho de 1876, o Secretário de Polícia da Bahia, João Bernardo Magalhães, solicitou ao seu colega do Ceará, Vicente Paulo Descals Teles, que impedisse o acusado de voltar à Bahia, mesmo que ele fosse declarado inocente das acusações, o que realmente aconteceu. Lá foi ele posto em liberdade.</p>
                    <p>Durante esse pouco tempo na Bahia, o jornal “Diário da Bahia” escreveu sobre ele: “ Se Antonio Conselheiro não é um grande hipocrita que, sob suas humildes aparências, oculta algum “tartufo” de nova espécie, não passa de um fanático. Será um criminoso? Dir-nos-há a policia que ordenou sua captura”.</p>
                    <p>Em 1877 é citado pela “Folhinha Laemmert”, do Rio de Janeiro, como Antonio Conselheiro, um pregador de grande influência sobre os sertanejos, sem muitos cuidados com o asseio pessoal, barbudo, cabeludo, e vestido com uma túnica de algodão e alimentando-se tenuamente, parecendo uma múmia.</p>
                    <p>Dedicava-se a rezar terços e ladainhas e a pregar e a dar conselhos às multidões. Não comia carnes, mas apenas cereais. Não dormia em camas ou em redes, mas apenas em tábuas, bancos ou no chão. E só aceitava ajuda suficiente para as suas necessidades. Nas suas peregrinações era seguido por um grupo de sertanejos, homens e mulheres. Ele levava à frente um oratório, que Edmundo Moniz descreve assim:</p>
                    <blockquote>Em sua peregrinação, Antonio Conselheiro trazia um pequeno oratório com a imagem de Jesus, carregado por dois de seus adeptos. Nas horas de preces, penduravam-no respeitosamente no galho de uma árvore. E todos os peregrinos ajoelhavam-se rezando e cantando. Depois, carregavam o oratório em triunfo e era assim que o Conselheiro, em meio das ladainhas, entrava solenemente nos povoados.</blockquote>
                    <p>Essa maneira de Antonio Conselheiro fazer as suas peregrinações se assemelhava à caminhada de Davi em direção a Jerusalém, em cujo trajeto a arca ia à frente, conforme narração de II Samuel 6:1-5, que transcrevo numa tradução da linguagem de hoje, da Sociedade Bíblica do Brasil:</p>
                    <blockquote>Mais uma vez Davi reuniu os melhores soldados de Israel, num total de trinta mil homens. Levou-os à cidade de Baalá, em Judá, para pegarem a arca do acordo, que tem o nome do Deus Todo-Poderoso, que se assenta no seu trono, entre os querubins. Colocaram a arca num carro de bois, novo, e a tiraram da casa de Abinadabe, que ficava num monte. Uzá e Aiô, filhos de Abinadabe, guiavam o carro que carregava a arca. Aiô caminhava na frente. Davi e todos os israelitas dançavam e cantavam com todas as suas forças em louvor ao Deus Eterno. Eles tocavam harpas, liras, tambores, castanholas e pratos.</blockquote>
                    <p>Em sua peregrinação Antonio Conselheiro ia aumentando sempre o número de seguidores. Eram artesãos, pequenos proprietários de terra expulsos pelos latifundiários, migrantes, escravos alforriados, escravos fugidos e pessoas comuns.</p>
                    <p>Nas paradas e nos povoados onde chegavam, Antonio Conselheiro pregava os seus sermões de maneira clara, simples, mas corajosa e eloqüente. Citava os Evangelhos em latim, com a devida tradução. Juntava a pregação a uma vida ascética. A vida que levava e os sermões que pregava encantavam os sertanejos.</p>
                    <p>Mas o Conselheiro impressionava os seus seguidores também pela sua maneira de ser:</p>
                    <p>Ele aparecia sempre com face emoldurada por longas barbas brancas, cabelos escorridos sobre os ombros, envolto numa túnica azul de brim americano, trazendo nas costas um surrão de couro onde guardava livros, papel e tinta, sempre seguido por numerosos partidários. Usava um chapéu de largas abas com fitas caídas. Apoiado em seu cajado, caminhava de arraial a arraial, pregando a salvação dos homens por meio das boas obras. Totalmente independente do Estado e da Igreja, opunha-se à ordem social baseada no latifúndio e na exploração dos camponeses.</p>
                    <h4>6. A preocupação social de Antonio Conselheiro</h4>
                    <p>O discurso religioso do Conselheiro não era alienante. Era seriamente comprometido com a realidade do povo sertanejo, o que ajuda a explicar a adesão crescente durante as suas andanças. Explica também a sua reação contra atitudes municipais decorrentes da mudança do regime monárquico para o republicano. Mas vai mais adiante. Ele revela uma sensibilidade toda especial com a questão da escravatura. Se, por um lado, era contra reformas políticas, era amplamente favorável a todas as leis em benefício dos escravos. Para ele, a abolição da escravatura tinha a aprovação divina.</p>
                    <h4>7.Antonio Conselheiro em Belo Monte</h4>
                    <p>Em Belo Monte o Conselheiro vivia cercado de cuidados especiais. João Félix, o Taramela, era o responsável pela relação do povoado com ele. Era também quem encaminhava ao Conselheiro as pessoas que queriam falar com ele. Recebia os cuidados de oito beatas que zelavam por sua vida pessoal.</p>
                    <p>Ao contrário do que se imagina, Antonio Conselheiro se mantinha limpo e asseado. Vestia-se de uma túnica azul, tinha longa barba branca e os cabelos caídos sobre os ombros, bem cuidados. Vivia sempre isoladamente e quando saia no povoado usava, além do roupão azul, um longo chapéu de abas largas e caídas, rodeado de fitas pretas. Era respeitado e reverenciado por todos e tinha o controle absoluto do povoado. Ninguém entrava no povoado sem o seu consentimento.</p>
                    <h4>9. Despedida e morte do Conselheiro</h4>
                    <p>A vida espartana e a angústia da guerra debilitavam o Conselheiro. Ele pressentia o seu fim. No dia 12 de janeiro de 1897, Fez um sermão que pode ser considerado como de despedida:</p>
                    <p>Praza aos céus que abundantes frutos produzam os conselhos que tendes ouvido; que ventura para vós se assim o praticardes; podeis entretanto estar certos de que a paz de Nosso Senhor Jesus Cristo, nossa luz e força, permanecerá em vosso espírito. Ele vos defenderá das misérias deste mundo; um dia alcançareis o prêmio que o Senhor tem preparado (se converterdes sinceramente para Ele) que é a glória eterna. Como não ficarei plenamente satisfeito sabendo da vossa conversão, por mim tão ardentemente desejada. Outra coisa, porém, não é de esperar de vós à vista do fervor e animação com que tendes concorrido para ouvirdes a palavra de Deus, o que é uma prova que atesta o vosso zelo religioso. Antes de fazer-vos a minha despedida, peço-vos perdão se nos conselhos vos tenho ofendido. Conquanto em algumas ocasiões proferisse palavras excessivamente rígidas, combatendo a maldita república, repreendendo os vícios e movendo o coração ao santo temor e amor de Deus, todavia não concebam que eu nutrisse o mínimo desejo de macular a vossa salvação (que fala mais alto do que tudo quanto eu pudesse aqui deduzir) me forçou a proceder daquela maneira. Se porém se acham ressentidos de mim, peço-vos que me perdoeis pelo amor de Deus. É chegado o momento para me despedir de vós; que pena, que sentimento tão vivo ocasiona esta despedida em minha alma, à vista do modo benévolo, generoso e caridoso com que me tendes tratado, penhorando-me assim bastantemente! São estes os testemunhos que me fazem compreender quanto domina em vossos corações tão belo sentimento! Adeus, povo, adeus aves, adeus árvores, adeus campos, aceitai a minha despedida, que bem demonstra as gratas recordações que levo de vós, que jamais se apagarão da lembrança deste peregrino, que aspira ansiosamente a vossa salvação e o bem da Igreja. Praza aos céus que tão ardente desejo seja correspondido com aquela conversão sincera que tanto deve cativar o vosso afeto.</p>
                    <h3>II. BELO MONTE</h3>
                    <p>Canudos não surgiu por acaso e nem da noite para o dia. Surgiu no momento certo, depois de anos de peregrinação e do constante aumento de seguidores.</p>
                    <h4>1.Como tudo começou</h4>
                    <p>As andanças estavam chegando ao fim. Em junho de 1893, Antonio Conselheiro, já então acompanhado por um contingente de cerca de seiscentas pessoas, acamparam no sertão da Bahia, às margens do rio Vaza-Barris e ocuparam uma fazenda abandonada. O rio Vaza-Barris, que chegava a ter 100 metros de largura, oferecia água com fartura para tudo na comunidade.</p>
                    <p>O local, em 1890, não passava de uma fazenda abandonada, com a casa do proprietário, a capela e cerca de 50 casebres em ruínas, Logo, logo, o que acontecia em Canudos despertou a atenção dos arraiais, povoados e fazendas ao redor da região. De todas as partes chegavam famílias de trabalhadores à comunidade de Belo Monte. Essa migração provocou uma crise séria de mão-de-obra barata na região, levando o Barão de Geremoabo a escrever que alguns lugares da região no Estado e de Sergipe estavam ficando desabitadas pelas fugas de famílias inteiras para Canudos.</p>
                    <h4></h4>
                    <p>2.Como vivia a comunidade</p>
                    <p>A comunidade de Belo Monte era constituída de gente de diversas origens e situações: brancos famintos do Nordeste, negros ex-escravos e índios das tribos Tuxá, de Rodelas; Kaibé, da região de Euclides da Cunha; e Kiriri, de Banzaê.</p>
                    <p>Belo Monte era uma comunidade fraterna, solidária e de fé. O cotidiano consistia no trabalho durante o dia e oração à noite. Trabalhavam durante o dia na agricultura e no criatório de cabras, na construção das casas e na administração do povoado, que crescia sem parar. Normalmente, todos participavam das atividades diárias: homens, mulheres e crianças.</p>
                    <p>A comunidade vivia de maneira ordeira e organizada, sem a existência de leis e delegacias. A proibição de prostíbulos, bares e a venda de cachaça muito contribuiam para isso. As atividades eram divididas de acordo com a idade e o sexo e muitos dos serviços eram feitos em regime de mutirão. Havia oficinas para fabricação e reparo das ferramentas para a lavoura, mas usadas também, no período da guerra, para fabricação e reparo de armas; as crianças eram educadas nas duas escolas existentes no arraial; os trabalhadores da terra cultivavam milho, feijão, mandioca, melancia, abóbora e cana-de-açucar; outros se dedicavam à criação de gado, de caprinos e ovinos, suínos e aves; parte da população se dedicava ao artesanato; as costureiras, confeccionando roupas; o sapateiros, fazendo sapatos e alpercatas; as beatas, rezando e cuidando da igreja e do Santuário, espaço onde via o Conselheiro.</p>
                    <p>Canudos chegou a ser autosuficiente na produção de alimentos. Alguns produtos excedentes eram exportados para Geremoabo, Monte Santo e Uauá. Para os canudenses, marcados pela orientação do líder, a terra, o pasto e a produção eram comuns a todos; ao longo e nas margens do Vaza-Barris foram feitos pequenos açudes, que possibilitavam a irrigação das plantações dos legumes e das verduras; o que Canudos produzia era mais do que suficiente para o consumo interno, possibilitando a venda do excedente para fora do arraial. O criatório de cabras cresceu tanto que se tornou um dos maiores do Nordeste. As cabras ofereciam carne e leite, mas sobretudo ofereciam peles que, curtidas, serviam para calçados, roupas e selas, que eram muita apreciadas. Canudos chegou a possuir dezenas de curtumes e as peles “Uauá” e “Curaçá” eram cotadas entre as melhores no comércio para exportação para a Alemanha.</p>
                    <p>Honório Vila Nova, um dos sobreviventes do massacre, numa entrevista ao escritor Nertan Macedo afirmou: Grande era canudos do meu tempo. Quem tinha roça, trabalhava na beira do rio. Quem tinha gado, tratava do gado. Quem tinha mulher e filhos, tratava da mulher e dos filhos. Quem gostava de rezar, ia rezar. De tudo se tratava, porque a nenhum pertencia, era de todos, pequenos e grandes, na regra ensinada pelo Peregrino”. (32)</p>
                    <p>Denise dos Santos Poncio (1997) apresenta a relação dos comerciantes exclusivos de Canudos: Antonio da Mota era comerciante de couro e balcão e dono de terras; Joaquim Macambira era agricultor e comerciante, ambos já vivendo na região antes da chegada do Conselheiro e seus seguidores; o cearense Antonio Vilanova, comerciante, dono das melhores casas de negócio do arraial; e Jesuino Correia Lima, o capitão jagunço, considerado um traidor por ter se tornado guia das expedições. (33)</p>
                    <p>Mas Havia outros com funções diferentes na comunidade: João Abade, um dos principais chefes de Canudos, era pelos canudenses chamado de Chefe do Povo, Comandante de Rua. João Abade, moreno escuro, de voz imperativa e forte, sempre bem vestido, era o braço direito do Conselheiro.</p>
                    <p>Pajeú, substituto eventual de João Abade, era alto e forte e um guerreiro incansável no teatro da guerra. Carregava em uma das mãos a espingarda para lutar contra os soldados e na outra o cacete para estimular os canudenses.</p>
                    <p>Pedrão, mestiço alto e forte. Comandava os canudenses em diversas operações durante a guerra.</p>
                    <p>Macambira, já idoso, era inteligente, ardiloso e especialista nas emboscadas contra as investidas militares.</p>
                    <p>Manoel Quadrado era tranqüilo e inofensivo. Mantinha uma vida isolada, dedicando-se à pesquisa das folhas e raízes da região, que usava para curar os habitantes do arraial. Era o curandeiro do arraial, ou melhor, o médico naturalista do arraial.</p>
                    <p>José Félix, o Taramela, era quem cuidava do santuário e da igreja. Era uma espécie de auxiliar do Conselheiro e o seu escudeiro. Tinha sob as suas ordens oito beatas que tinham a tarefa de zelar pela vida pessoal do Conselheiro, como preparar o seu banho diário, lavar a sua roupa e preparar a sua comida, que era muito frugal. Também cuidavam das fogueiras para a vestidas de roupas azuis, com cordas de linho cingidas na cintura. Eram autênticas beatas que guiavam o povo nas reuniões diárias do final da tarde e início da noite.</p>
                    <p>O Conselheiro vivia sob a proteção especial de um grupo selecionado dentre os que compunham a comunidade, chamado de Guarda Católica e conhecido também como Companhia do Bom Jesus. Os que cometiam erros eram colocados na “poeira”, uma prisão provisória, até que fossem levados para a prisão fora do arraial.</p>
                    <p>Em Canudos havia três templos: uma capela, já existente na fazenda, e muito provavelmente, transformada em santuário que serviu de residência, sede e túmulo do Conselheiro; uma igreja inacabada, dedicada ao Bom Jesus e pivor da guerra, e a pequena igreja construída pelo povo do arraial em louvor a Santo Antonio. Esta igreja era objeto do cuidado do povo, que também cuidava das rezas, dos cantos e benditos, pois em Canudos, as noites eram dedicadas à oração. Rezavam o terço, a ladainha, o Ofício da Mãe de Deus, a Missa e ouviam o sermão pregado pelo Conselheiro. Ataliba Nogueira descreve alguns dos momentos dos sermões de Antonio Conselheiro: </p>
                    <blockquote>Cometem grave pecado aqueles que não santificam o Dia do Senhor. Aqueles que não participam dos encontros da comunidade. Nestes encontros a gente honra a Deus que criou todas as coisas e descansou no sétimo dia. A gente também se encontra com os irmãos.</blockquote>
                    <blockquote>Quem não respeita o encontro da comunidade não tem temor ao Deus Onipotente, não respeita a sua vontade e não colabora com o seu projeto. Se querem gozar de felicidade completa, louvem ao Senhor participando dos encontros, ouvindo a Palavra de Deus, cantando e planejando a mudança da vida. Não atrapalhem, não semeiem a desunião, nem desanimem os companheiros de luta.</blockquote>
                    <p>Com o passar do tempo Antonio Conselheiro passou a ser idolatrado. Era chamado de Antonio dos Mares, Irmão Antonio, Santo Antonio Aparecido, Santo Conselheiro, Bom Jesus Conselheiro, Senhor do Bonfim, Bom Jesus ou Conselheiro.</p>
                    <h3>III. AS REAÇÕES CONTRA CANUDOS</h3>
                    <p>Até o golpe final sobre Canudos, muita coisa aconteceu. Canudos, na verdade, começou a morrer bem antes.</p>
                    <h4>1.A reação contra Canudos</h4>
                    <h5>Dos latifundiários</h5>
                    <p>Os deslocamentos de trabalhadores para Canudos provocaram a ira dos fazendeiros que perdiam mão de obra barata. Em apoio a eles, senhores de engenho e coronéis do sertão logo se mobilizaram, atraindo a solidariedade de padres e bispos do sertão e de políticos do Nordeste. Conselheiro provocava a perda de prestígio de todos eles e atraia a atenção, o respeito e a admiração do povo sertanejo.</p>
                    <h5>Da Igreja</h5>
                    <p>A reação da Igreja contra o Conselheiro começou logo cedo e se estendeu até à destruição da Comunidade de Belo Monte. Alguns padres manifestavam consideração e respeito pelo Conselheiro, mas outros assumiram postura crítica e violenta.</p>
                    <p>Mesmo antes da formação da Comunidade de Belo Monte o Conselheiro já sofria perseguição. Ao se formar a Comunidade, ela aumentou. Houve o caso do Padre Júlio Fiorentini que, devidamente autorizado pelo arcebispo de Salvador, D. Luiz dos Santos, iniciou uma campanha sistemática contra o Conselheiro e seus seguidores, chamando-os de assassinos e jagunços. Chegou até a excomungar o Conselheiro. A situação ficou tão séria que o arcebispo pediu ao Governador que dispersasse o povo de Belo Monte, no que não foi atendido.</p>
                    <p>A última tentativa da Igreja de submeter Canudos se deu com o capuchinho italiano, frei Evangelista do Monte Marciano, enviado pelo novo arcebispo da Diocese da Bahia, D. Jerônimo Tomé. O comportamento do religioso no arraial provocou a ira dos conselheiristas, obrigando-o a sair às pressas. O relatório do Frei Evangelista acusava Canudos de ser um foco de superstição, fanatismo e um cisma na igreja baiana. Como as tentativas da Igreja falharam, só restava agora usar o Estado. E a ele a Igreja se aliou.</p>
                    <h5>Das autoridades políticas</h5>
                    <p>A reação política que já havia começado no interior, com os desentendimentos entre o Coronel Cícero Dantas Martins, o Barão de Geremoabo e o Governador do Estado da Bahia, Luiz Viana, se amplia com a atenção do Governador ao telegrama recebido do Juiz Arlindo Leoni, de Juazeiro, que informava que o povo do Conselheiro iria invadir e saquear Juazeiro. Esse Juiz, na verdade, já havia tido sérios desentendimentos com Antonio Conselheiro. Com o atendimento do Governador, tem início à saga do que conhecemos como as quatro expedições de guerra contra Canudos.</p>
                    <p>Uma avaliação crítica de Canudos que merece atenção é a feita por Ruy Barbosa, em Salvador, em agradecimento por sua reeleição para o Senado. Longe de identificar Canudos como um movimento político de resistência contra a República e, portanto, uma rebelião em favor da monarquia, ele não poupa palavras de desprezo e escárnio sobre o arraial de Belo Monte e o Conselheiro:</p>
                    <blockquote>Canudos é apenas um acidente monstruoso das aluviões morais do sertão: a truculência das lutas primitivas, a rudeza dos instintos agrestes, a crendice da descultura analfabeta, o banditismo predatório do crime, a pugnacidade implacável dos ódios locais, a escória promíscua do campo e da cidade, as fezes do ócio, da miséria, da tarimba e da penitenciária; todos esses sedimentos orgânicos da anarquia, derivados, de todos os pontos do Brasil, para um estuário comum nos anseios longínquos do nosso interior e incubados ali, cerca de vinte anos, em tranqüila fermentescência pela fascinação de um iluminado, pelo tresvario de uma alucinação supersticiosa. Essa formação anômala e ameaçadora, tolerada, graças à sua primitiva aparência de inocente monomania religiosa, pela indulgência brasileira, durante mais, talvez de um vicênio, sob dois regimes sucessivos, devia naturalmente resultarem fenômeno desusado e fatal.</blockquote>
                    <h5>Da imprensa</h5>
                    <p>A terceira expedição colocou Canudos no centro das discussões políticas da incipiente república e do Brasil inteiro. E, naturalmente, despertou a atenção da mídia da época, restrita a jornais e rádios. Um dos mais ilustres correspondentes da guerra foi Euclides da Cunha, engenheiro militar reformado e jornalista. Foi de São Paulo para Canudos cobrir a guerra como correspondente do jornal O Estado de São Paulo e adido-militar do Estado-Maior do Ministério da Guerra, acompanhando a quarta expedição. De seus artigos e de suas anotações brotaram o mais importante e célebre documento sobre Canudos, o livro Os Sertões, publicado em 1902. O livro faz uma denuncia do massacre de Canudos e, ainda hoje, é um clássico no estudo do assunto.</p>
                    <p>Devido a importância de Euclides da Cunha no cenário da guerra de Canudos, ofereço aqui mais algumas informações a respeito desse ilustre personagem, testemunha dos acontecimentos do País no final do século XIX.</p>
                    <p>Tendo o presidente da República, Prudente de Morais, atendido o pedido de Júlio Mesquita, do jornal O Estado de São Paulo, nos termos em que foi solicitado, Euclides da Cunha embarcou para o Rio de Janeiro no dia 01 de agosto de 1897, para se apresentar ao Ministro da Guerra, Marechal Machado Bittencourt, a fim de se incorporar à Quarta Expedição.</p>
                    <p>Do Rio de Janeiro foi para Salvador, de navio, e de lá, no dia 20 de agosto, de trem, viajou para Alagoinhas e Queimadas. Dali, a cavalo, passou por Tanquinho, Cansanção, Quirinquinquá e Monte Santo, de onde chegou a Canudos em 16 de setembro. Muitas reportagens de Euclides da Cunha foram escritas durante a viagem. Nenhuma delas de Canudos. Euclides deixou Canudos no dia 3 de outubro, tendo chegado em Salvador no dia 13. É exonerado de suas funções de adido militar do exército e embarca de volta para o Rio de Janeiro. Vai, a partir de então, cuidar da publicação de seu livro, já devidamente planejado em suas conversas na Bahia.</p>
                    <p>Mas, também do Rio de Janeiro houve cobertura jornalística sobre a Guerra de Canudos, através do jornal do Comércio. Da Bahia, teatro da guerra, quatro jornais faziam cobertura: O Diário de Notícias, o Correio de Notícias, o Diário da Bahia e o A Bahia. Os jornais baianos tiveram uma grande atuação na cobertura jornalística da Guerra de canudos e se constituem em fonte de pesquisa até hoje. Ao longo deste livro há muitas referências às reportagens dos jornais da Bahia sobre Canudos.</p>
                    <h5>Dos movimentos organizados</h5>
                    <p>Nesse período das expedições militares enviadas contra Canudos, as reações contra o Arraial aconteciam nos centros urbanos, que concentravam o mundo político e intelectual da Capital baiana e do país.</p>
                    <p>No dia 18 de março de 1897 foi divulgado o Manifesto dos Estudantes de Medicina. Era um manifesto contra o Conselheiro, feito pelos estudantes das Escolas Superiores da Bahia. O Manifesto dos estudantes de Direito denunciava os excessos dos militares contra Canudos.</p>
                    <h4>IV. O FIM DE CANUDOS</h4>
                    <p>Nada havendo que pudesse destruir Canudos, nenhuma força capaz de eliminar aquela gente, foi decidido, então, fazer-se uso da força das armas. E quatro expedições, em quatro ocasiões diferentes, comandadas por oficiais militares progressivamente mais graduados, foram enviada sobre Canudos.</p>
                    <p>A primeira expedição: É composta de 104 homens e chefiada pelo Tenente Pires Ferreira. O combate tem início na manhã de 21 de novembro de 1896, no arraial de Uauá, hoje um Município importante no sertão, maior criador de caprinos do mundo. Foi uma luta sangrenta, na qual morreram muitos combatentes dos dois lados. Derrotados, os soldados saqueiam o arraial e voltam para Juazeiro.</p>
                    <p>A segunda expedição. Em janeiro de 1897 tem início a mais uma tentativa de eliminação de Canudos. O contingente é comandado pelo major Febrônio de Brito. Foi também derrotado pelos canudenses que, a essa altura, já tinham consciência de que novas tentativas militares iriam se suceder. E se preparavam para os embates, muito embora também conscientes de que levavam nítida desvantagem em armas e munições.</p>
                    <p>A terceira expedição. Foi comandada pelo temível coronel Moreira César e teve início no dia 2 de março de 1897. Também ela foi derrotada, de maneira heróica pelos defensores do Arraial de Belo Monte. A derrota humilhou e provocou reação violenta no governo. E de lá sai a ordem de destruição total de Canudos. É no contexto dessa terceira expedição que se dá o discurso de Rui Barbosa na Bahia.</p>
                    <p>É assim que tem início à quarta expedição. Comandada pelo General Artur Oscar, recebe reforços militares de todo o País. Junto com o General Artur Oscar vão três generais, numerosos coronéis, majores, capitães e tenentes e cerca de dez mil soldados, num exército de vinte mil. Durou muitos meses, de 4 de novembro de 1896 a 5 de outubro de 1897, e por vezes, esteve prestes a ser destroçada, não só pela resistência dos canudenses, como pelos problemas enfrentados pelos soldados, como febre amarela, tuberculose, varíola e fome. Salvou-se graças ao grande reforço que recebeu quando se achava em perigo, o que representou, pode-se dizer, uma quinta expedição.</p>
                    <p>Esse reforço veio através do envolvimento do próprio Ministério da Guerra, à frente o Marechal Machado Bittencourt, que se deslocou do Rio de Janeiro no navio Espírito Santo, no dia 3 de agosto, chegando em Salvador no dia sete. Entre a preparação das expedições e as batalhas travadas, a Campanha de Canudos durou de 4 de novembro de 1896 a 6 de outubro de 1897. Não se tratava de uma simples insurreição de sertanejos e sim de uma guerra civil. (36)</p>
                    <p>Canudos acabou sem se render</p>
                    <p>Com a vitória da quarta expedição o sonho de Belo Monte havia chegado ao fim. As casas tinham sido incendiadas, ensangüentaram o arraial e destruíram as terras. No dia seguinte, 6 de outubro de 1897, logo pela manhã, sob os escombros do arraial e o mau cheiro dos corpos estendidos pelo chão, o Exército procurava o cadáver de Antonio Conselheiro, falecido poucos dias antes do desfecho da guerra.</p>
                    <p>Antonio Conselheiro havia morrido duas semanas antes do final do massacre. Não morreu pelas balas do canhão, mas por problemas pessoais de saúde. Após a destruição do povoado, localizaram o seu corpo, cuidaram de desenterrá-lo, fotografá-lo, cortar-lhe a cabeça e depois voltar a sepultar o corpo. A cabeça foi levada para Salvador, para exame médico e depois ser exibida para a visitação pública, na Escola de Medicina, no Terreiro de Jesus. Em 1905 um incêndio destruiu a Faculdade.</p>
                    <p>Em Salvador o crânio de Antonio Conselheiro foi submetido a exames médico-legais e antropológicos, a fim de se ter o veredito de cientistas sobre a sua sanidade mental. Os exames do crânio foram feitos pelos médicos Nina Rodrigues e Sá de Oliveira. Nina Rodrigues escreveu no laudo que “o crânio de Antonio Conselheiro não apresentava nenhuma anomalia que denunciasse traços de degenerescência: é um crânio de mestiço, onde se associam caracteres antropológicos de raças diferentes”.</p>
                    <p>Belo Monte acabou. Euclides da Cunha escreveu assim o seu final:</p> 
                    <p>Canudos não se rendeu. Exemplo único em toda a história, resistiu até o esgotamento completo. Expugnado palmo a palmo, na precisão integral do termo, caiu do dia 5, ao entardecer, quando caíram seus últimos defensores, que todos morreram. Eram quatro apenas: um velho, dois homens feitos e uma criança, na frente dos quais rugiam raivosamente cinco mil soldados.</p>
                    <p>Hoje a gente se pergunta: por que isso aconteceu? Luitgarde, num texto sobre Ibiapina, Pe. Cícero e Conselheiro, faz algumas afirmações que ajudam a compreender esse drama. Extraimos a parte correspondente a Canudos:</p>
                    <blockquote>... Refratário à riqueza, desgarrado de quaisquer laços com a hierarquia governante, Conselheiro é exposto à tragédia pelo poder do Estado (governo, polícia, juízes e exército), pelo poder da Igreja (Bispo da Bahia), atiçado pelos intelectuais republicanos, sucumbindo com seu povo à impossibilidade de entendimento por parte das camadas dominantes, de suas concepções de mundo, autodidata, limitado politicamente pelos horizontes de seu mundo, Conselheiro carrega atônito a dor da injustiça maior de sua vida, o genocídio de um povo que, por sua perspectiva, apenas vivia a palavra de Deus na Terra: trabalhar, rezar, procriar, e fazer o bem... (38)</blockquote>
                    <h5>A tristeza dos cachorros</h5>
                    <p>Mas o que, por ódio ou interesses mesquinhos, deixou de prevalecer no tratamento sobre Canudos, os cães fizeram. O relato e de Olavo Bilac:</p>
                    <blockquote>Havia no arraial, um grande número de cães. Cada jagunço tinha o seu cão – companheiro fiel que o acompanhava às caçadas, às batidas do mato, às caminhadas longas pelo sertão velho. Quando o sítio começou, os animais ficaram, como os homens, encurralados no arraial, de orelhas a fito, farejando o perigo, latindo ao luar, alta noite, vigiando as entradas dos desfiladeiros em que o Conselheiro residia com o seus exércitos de jagunços. Mas quando, feroz, o bombardeio principiou a derrubar as casas, os cães abalaram, desvairadamente, fugindo da metralha: não podiam ter a inabalável fé, a crença ardente dos jagunços, nem sobre a alma deles podia ter influência a palavra ardente do Messias sertanejo...</blockquote>
                    <blockquote>Não viram arderem as casas, varadas de balas, comidas pelas chamas do querosene; não viram a chacina última, não assistiram ao trágico horror da derrota, não ouviram o fragor vitorioso das bandas de música invadindo o reduto conquistado: andavam pelo mato, famintos e aturdidos, vagabundos, chorando os donos ausentes.</blockquote>
                    <blockquote>Depois, quando cessou o clamor da artilharia, quando os batalhões recolheram a Monte Santo, quando apenas um punhado de soldados ficou guardando Canudos – ei-los de volta, magros, descarnados, ansiosos, de focinho no chão, pelas ruas desertas da cidadela, cheirando o sangue empoçado, uivando melancolicamente na solidão e no silêncio das ruínas. E o oficial que narrou o caso ao jornal baiano conta que viu muitos deles empenhados em cavar a terra, em descobrir os cadáveres podres, em farejá-los longamente, procurando descobrir os donos, os antigos companheiros das caçadas, das batidas do mato, das caminhadas longas pelo sertão velho...</blockquote>
                    <blockquote>E assim Canudos chegou ao fim. Para acabar definitivamente, o arraial foi coberto pelas águas do hoje denominado Açude do Cocorobó.</blockquote>
                    <p>Mas Canudos não morreu. Canudos ressurgiu! Ressurgiu na história do País, hoje recontada por historiadores comprometidos com a verdade; no testemunho dos descendentes dos canudenses; no trabalho de pesquisa feita no Brasil e fora do país; nos movimentos religiosos e sociais do Nordeste e na fé imorredoura dos sertanejos que nunca deixaram de acreditar no beato Conselheiro.</p>
                    <q>Texto extraído do livro “Canudos, Uma Utopia Religiosa”, no prelo.<q>
                    <p class="direita">Salvador, outubro de 2013.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">	
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <div class="artigo">
                    <h2></h2>
                    <cite><cite>
                    <p></p>
                    <p></p>
                    <p></p>
                    <p></p>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>